image_prompts = [
    "View of a calm ocean at sunset with waves gently lapping against the shore",
    "Stormy ocean with dark clouds and lightning striking in the distance",
    "Crystal-clear tropical ocean with vibrant coral reefs and colorful fish",
    "Peaceful forest at dawn with sunlight filtering through tall trees and a gentle mist",
    "Dense, lush forest with tall ancient trees and soft moss covering the ground",
    "Magical forest with glowing plants and small creatures scurrying around",
    "Snow-capped mountains under a clear, starry night sky with a full moon",
    "Rolling green hills with scattered wildflowers and a clear blue sky",
    "Rocky mountain peaks covered in mist with an eagle soaring in the distance",
    "Futuristic cityscape with tall skyscrapers and flying cars at night",
    "Quiet street in a European village with cobblestone paths and cozy houses",
    "Bustling modern city with people walking along the sidewalk and traffic passing by",
    "Endless desert with golden sand dunes under a hot midday sun",
    "Desert landscape with a single cactus and a colorful sunset",
    "Winding road through a rocky desert with mountains in the background",
    "Coral reef teeming with vibrant marine life and sunbeams piercing the water surface",
    "Deep ocean scene with mysterious fish and faint bioluminescent lights",
    "Shipwreck at the bottom of the ocean with schools of fish swimming around",
    "Ancient castle on a cliff overlooking a vast sea under a purple twilight sky",
    "Floating islands with waterfalls cascading into the clouds and lush green forests",
    "Enchanted forest with glowing flowers, soft light, and mythical creatures",
    "Aurora borealis over a snowy mountain landscape with trees covered in frost",
    "Waterfall in a tropical jungle with a rainbow forming in the mist",
    "Sunset over a field of blooming lavender with a warm, golden glow"
]
